### PR TITLE
support building with GHC 8.2.1

### PR DESCRIPTION
**Pull request by agentm**
increase minimum network-transport-tcp version in test
all tests pass

The remaining issue is a lot of warnings looking like this:
```
src/Control/Distributed/Process/Async.hs:245:18: warning: [-Wsimplifiable-class-constraints]
    • The constraint ‘Serializable a’ matches an instance declaration
      instance (binary-0.7.6.1:Data.Binary.Class.Binary a,
                base-4.10.0.0:Data.Typeable.Internal.Typeable a) =>
               Serializable a
        -- Defined in ‘Control.Distributed.Process.Serializable’
      This makes type inference for inner bindings fragile;
        either use MonoLocalBinds, or simplify it using the instance
    • In the type signature:
        waitAnyCancel :: (Serializable a) =>
                         [Async a] -> Process (Async a, AsyncResult a)
```

### CODE REVIEW

**Comment by agentm** [comment]
This issue is blocking [our project's](https://github.com/agentm/project-m36) GHC 8.2 support.

**Comment by lorenzo** [comment]
Is there anything I can help with to get this merged? I would really like to use the latest GHC for my project

**Comment by qnikst** [comment]
I've merged manually using github provided commands, seems that it didn't preserve authorship of the PR. Is that ok?

**Comment by qnikst** [comment]
Update I've fixed version on hackage, but tests can be run only with `--allow-newer` due to `distributed-process-systest` dependency. I'll try to see what can I do there.

**Comment by agentm** [comment]
Thanks for merging! GHC 8.2 support would help us a lot!

**Comment by lorenzo** [comment]
Thanks so much!

**Comment by hyperthunk** [comment]
d-p-systest has been updated, but there are now unresolved merge conflicts...

**Comment by agentm** [comment]
GHC 8.2 support is very important to us and we are willing to put in whatever work necessary to complete it. Please let me know how we can help. 

Thanks for updating these packages on hackage- we discovered that d-p-extras has an outdated bounds. That may be one of the few, final issues preventing 8.2 support.

**Comment by qnikst** [comment]
@agentm I've resolved conflicts, let me wait for CI results and merge! Thanks for your work!

**Pull request merged**
